export const INCREMENT_LIKES = 'INCREMENT_LIKES';
export const DECREMENT_LIKES = 'DECREMENT_LIKES';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
